# Generated by Django 5.0.14 on 2025-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='village_cards/', verbose_name='Превью поселка')),
                ('photo_village', models.ImageField(blank=True, null=True, upload_to='villages/', verbose_name='Фото Поселка')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='цена за сотку')),
                ('distance_mkad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Расстояние от МКАД')),
                ('communications', models.CharField(blank=True, max_length=250, null=True, verbose_name='Коммуникации')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube или RuTube', null=True, verbose_name='Ссылка на видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'Поселок',
                'verbose_name_plural': 'Поселки',
            },
        ),
    ]
