# Generated by Django 5.0.14 on 2025-07-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес поселка'),
        ),
    ]
