# Generated by Django 5.0.14 on 2025-07-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0002_village_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='yandex_map_embed',
            field=models.TextField(blank=True, help_text='Полный HTML-код iframe из Яндекс.Карт', null=True, verbose_name='Код iframe Яндекс.Карт'),
        ),
    ]
