# Generated by Django 5.0.14 on 2025-06-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_houseimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseimage',
            old_name='images',
            new_name='image',
        ),
    ]
