# Generated by Django 5.0.14 on 2025-06-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип партнера')),
                ('registration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оформление')),
                ('reservation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Платная бронь')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('yandex_map', models.TextField(blank=True, null=True, verbose_name='яндекс карта')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
